services:
  # Service MySQL pour la base de données de WordPress
  mysqlwordpress:
    image: mysql:lts
    container_name: mysql_db_wordpress
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress  # Base de données principale pour WordPress
      MYSQL_USER: wpuser         # Utilisateur principal pour WordPress
      MYSQL_PASSWORD: wppassword # Mot de passe principal pour WordPress
    volumes:
      - mysql_data_wordpress:/var/lib/mysql
    ports:
      - "3308:3306"  # Expose MySQL pour que WordPress puisse y accéder

  # Service MySQL pour la base de données de Zabbix
  mysqlzabbix:
    image: mysql:lts
    container_name: mysql_db_zabbix
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zabbix       # Base de données principale pour Zabbix
      MYSQL_USER: zabbixuser       # Utilisateur principal pour Zabbix
      MYSQL_PASSWORD: zabbixpassword # Mot de passe principal pour Zabbix
    volumes:
      - mysql_data_zabbix:/var/lib/mysql
    ports:
      - "3307:3306"  # Expose MySQL pour que Zabbix puisse y accéder (notez que le port 3306 est interne)

  # Service WordPress
  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    environment:
      WORDPRESS_DB_HOST: mysqlwordpress:3306
      WORDPRESS_DB_NAME: wordpress    # Base de données WordPress
      WORDPRESS_DB_USER: wpuser       # Utilisateur de la base de données WordPress
      WORDPRESS_DB_PASSWORD: wppassword
    depends_on:
      - mysqlwordpress
    ports:
      - "8080:80"  # Mapping du port 80 vers 8080 pour accéder à WordPress via http://<VM_IP>:8080
    volumes:
      - wordpress_data:/var/www/html

  # Service Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix_server
    environment:
      DB_SERVER_HOST: mysqlzabbix
      MYSQL_DATABASE: zabbix         # Base de données Zabbix
      MYSQL_USER: zabbixuser         # Utilisateur de la base de données Zabbix
      MYSQL_PASSWORD: zabbixpassword
    depends_on:
      - mysqlzabbix
    ports:
      - "10051:10051"  # Mapping pour le port Zabbix server

  # Service Zabbix Web Interface
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix_web
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: mysqlzabbix
      MYSQL_DATABASE: zabbix         # Base de données Zabbix
      MYSQL_USER: zabbixuser         # Utilisateur de la base de données Zabbix
      MYSQL_PASSWORD: zabbixpassword
    depends_on:
      - zabbix-server
    ports:
      - "8081:8080"  # Mapping pour l'interface Web Zabbix sur le port 8081

volumes:
  mysql_data_wordpress:
  mysql_data_zabbix:
  wordpress_data:
